# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/joan/PycharmProjects/ThetaTrader/GUI/strategy_builder_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StrategyBuilder(object):
    def setupUi(self, StrategyBuilder):
        StrategyBuilder.setObjectName("StrategyBuilder")
        StrategyBuilder.resize(1036, 294)
        self.centralwidget = QtWidgets.QWidget(StrategyBuilder)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 201, 61))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("logo.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 15, 51, 31))
        self.label.setObjectName("label")
        self.ticker_in = QtWidgets.QLineEdit(self.centralwidget)
        self.ticker_in.setGeometry(QtCore.QRect(280, 20, 113, 21))
        self.ticker_in.setObjectName("ticker_in")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 15, 41, 31))
        self.label_2.setObjectName("label_2")
        self.spot_in = QtWidgets.QLineEdit(self.centralwidget)
        self.spot_in.setGeometry(QtCore.QRect(580, 20, 113, 21))
        self.spot_in.setObjectName("spot_in")
        self.b_go = QtWidgets.QPushButton(self.centralwidget)
        self.b_go.setGeometry(QtCore.QRect(410, 15, 91, 32))
        self.b_go.setObjectName("b_go")
        self.b_close = QtWidgets.QPushButton(self.centralwidget)
        self.b_close.setGeometry(QtCore.QRect(940, 220, 91, 32))
        self.b_close.setObjectName("b_close")
        self.div_in = QtWidgets.QLineEdit(self.centralwidget)
        self.div_in.setGeometry(QtCore.QRect(740, 20, 113, 21))
        self.div_in.setObjectName("div_in")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(700, 15, 31, 31))
        self.label_3.setObjectName("label_3")
        self.r_in = QtWidgets.QLineEdit(self.centralwidget)
        self.r_in.setGeometry(QtCore.QRect(900, 20, 113, 21))
        self.r_in.setObjectName("r_in")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(870, 15, 31, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_5.setObjectName("label_5")
        self.ticker_in_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ticker_in_2.setGeometry(QtCore.QRect(80, 70, 113, 21))
        self.ticker_in_2.setObjectName("ticker_in_2")
        self.ticker_in_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ticker_in_3.setGeometry(QtCore.QRect(280, 70, 113, 21))
        self.ticker_in_3.setText("")
        self.ticker_in_3.setObjectName("ticker_in_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 70, 71, 16))
        self.label_6.setObjectName("label_6")
        self.b_new_row = QtWidgets.QPushButton(self.centralwidget)
        self.b_new_row.setGeometry(QtCore.QRect(10, 142, 31, 21))
        self.b_new_row.setObjectName("b_new_row")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 50, 801, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pc_box = QtWidgets.QComboBox(self.centralwidget)
        self.pc_box.setGeometry(QtCore.QRect(100, 140, 77, 26))
        self.pc_box.setCurrentText("Put")
        self.pc_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.pc_box.setObjectName("pc_box")
        self.pc_box.addItem("")
        self.pc_box.addItem("")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 110, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(250, 110, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(390, 110, 51, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(500, 110, 61, 16))
        self.label_11.setObjectName("label_11")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 140, 141, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 140, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(490, 140, 81, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        StrategyBuilder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StrategyBuilder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        StrategyBuilder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StrategyBuilder)
        self.statusbar.setObjectName("statusbar")
        StrategyBuilder.setStatusBar(self.statusbar)

        self.retranslateUi(StrategyBuilder)
        QtCore.QMetaObject.connectSlotsByName(StrategyBuilder)

    def retranslateUi(self, StrategyBuilder):
        _translate = QtCore.QCoreApplication.translate
        StrategyBuilder.setWindowTitle(_translate("StrategyBuilder", "Strategy Builder"))
        self.label.setText(_translate("StrategyBuilder", "Ticker :"))
        self.label_2.setText(_translate("StrategyBuilder", "Spot :"))
        self.b_go.setText(_translate("StrategyBuilder", "Go!"))
        self.b_go.setShortcut(_translate("StrategyBuilder", "Return"))
        self.b_close.setText(_translate("StrategyBuilder", "Close"))
        self.b_close.setShortcut(_translate("StrategyBuilder", "Esc"))
        self.label_3.setText(_translate("StrategyBuilder", "Div :"))
        self.label_4.setText(_translate("StrategyBuilder", "r :"))
        self.label_5.setText(_translate("StrategyBuilder", "Stock Leg :"))
        self.label_6.setText(_translate("StrategyBuilder", "Avg Price :"))
        self.b_new_row.setText(_translate("StrategyBuilder", "+"))
        self.label_7.setText(_translate("StrategyBuilder", "Option Legs :"))
        self.pc_box.setItemText(0, _translate("StrategyBuilder", "Put"))
        self.pc_box.setItemText(1, _translate("StrategyBuilder", "Call"))
        self.label_8.setText(_translate("StrategyBuilder", "P/C"))
        self.label_9.setText(_translate("StrategyBuilder", "Expiration"))
        self.label_10.setText(_translate("StrategyBuilder", "Strike"))
        self.label_11.setText(_translate("StrategyBuilder", "Amount"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StrategyBuilder = QtWidgets.QMainWindow()
    ui = Ui_StrategyBuilder()
    ui.setupUi(StrategyBuilder)
    StrategyBuilder.show()
    sys.exit(app.exec_())

