# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/joan/PycharmProjects/ThetaTrader/GUI/TTGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThetaTrader(object):
    def setupUi(self, ThetaTrader):
        ThetaTrader.setObjectName("ThetaTrader")
        ThetaTrader.resize(651, 345)
        ThetaTrader.setAutoFillBackground(False)
        ThetaTrader.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ThetaTrader)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 201, 61))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("/Users/joan/PycharmProjects/ThetaTrader/GUI/logo.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 180, 221, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 100, 221, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 100, 221, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 180, 221, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        ThetaTrader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ThetaTrader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ThetaTrader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ThetaTrader)
        self.statusbar.setObjectName("statusbar")
        ThetaTrader.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(ThetaTrader)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(ThetaTrader)
        self.actionSave.setObjectName("actionSave")
        self.actionCopy = QtWidgets.QAction(ThetaTrader)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(ThetaTrader)
        self.actionPaste.setObjectName("actionPaste")
        self.menuFile.addAction(self.actionNew)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ThetaTrader)
        QtCore.QMetaObject.connectSlotsByName(ThetaTrader)

    def retranslateUi(self, ThetaTrader):
        _translate = QtCore.QCoreApplication.translate
        ThetaTrader.setWindowTitle(_translate("ThetaTrader", "MainWindow"))
        self.pushButton.setText(_translate("ThetaTrader", "Strategy Builder"))
        self.pushButton_2.setText(_translate("ThetaTrader", "Portfolio"))
        self.pushButton_3.setText(_translate("ThetaTrader", "Spread Analyser"))
        self.pushButton_4.setText(_translate("ThetaTrader", "PlaceholderBtn"))
        self.menuFile.setTitle(_translate("ThetaTrader", "File"))
        self.actionNew.setText(_translate("ThetaTrader", "Settings"))
        self.actionNew.setStatusTip(_translate("ThetaTrader", "Create new file"))
        self.actionNew.setShortcut(_translate("ThetaTrader", "Meta+N"))
        self.actionSave.setText(_translate("ThetaTrader", "Save"))
        self.actionCopy.setText(_translate("ThetaTrader", "Copy"))
        self.actionPaste.setText(_translate("ThetaTrader", "Paste"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThetaTrader = QtWidgets.QMainWindow()
    ui = Ui_ThetaTrader()
    ui.setupUi(ThetaTrader)
    ThetaTrader.show()
    sys.exit(app.exec_())
